"""Writes crates/acacia-molang/src/queries.rs: the names of the documented Molang queries. See README.md.

usage: queries.py [--tag TAG] [--file mojang-molang-queries.json]
"""
import argparse
import json
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / "crates" / "acacia-molang" / "src" / "queries.rs"
SOURCE = "https://raw.githubusercontent.com/Mojang/bedrock-samples/{tag}/metadata/molang_modules/mojang-molang-queries.json"

TEMPLATE = """//! Generated by tools/molang-oracle/queries.py from Mojang/bedrock-samples {tag}; do not edit.

use crate::compiler::Engine;

/// The name after `query.` of every documented query, sorted.
pub const QUERY_NAMES: [&str; {count}] = [
{names}
];

/// Queries that packs above the given engine version no longer have.
const REMOVED_AFTER: [(&str, Engine); {removed_count}] = [
{removed}
];

/// Whether a pack of that engine version can use `query.<name>`.
pub(crate) fn exists(name: &str, engine: Engine) -> bool {{
    QUERY_NAMES.binary_search(&name).is_ok() && !REMOVED_AFTER.iter().any(|(removed, last)| *removed == name && engine > *last)
}}
"""


def wrapped(items, width=116):
    lines, line = [], "   "
    for item in items:
        if len(line) + len(item) + 1 > width:
            lines.append(line)
            line = "   "
        line += " " + item
    return "\n".join([*lines, line])


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--tag", default="v1.26.50.4", help="bedrock-samples tag to fetch")
    parser.add_argument("--file", type=Path, help="an already downloaded mojang-molang-queries.json")
    args = parser.parse_args()

    text = args.file.read_text(encoding="utf-8") if args.file else urllib.request.urlopen(SOURCE.format(tag=args.tag)).read().decode("utf-8")
    queries = {query["name"].removeprefix("query."): query["version_ranges"] for query in json.loads(text)["queries"]}
    # A query whose only range ends was removed; one with a later range only changed its answer.
    removed = {name: ranges[0]["last_version"] for name, ranges in queries.items() if len(ranges) == 1 and "last_version" in ranges[0]}
    OUT.write_text(
        TEMPLATE.format(
            tag=args.tag,
            count=len(queries),
            names=wrapped(f'"{name}",' for name in sorted(queries)),
            removed_count=len(removed),
            removed="\n".join(f'    ("{name}", Engine({last.replace(".", ", ")})),' for name, last in sorted(removed.items())),
        ),
        encoding="utf-8",
        newline="\n",
    )
    print(f"{len(queries)} queries, {len(removed)} removed in later versions -> {OUT}")


if __name__ == "__main__":
    main()
