//! Replays tests/fixtures/bedsim.json (generated by tools/diffharness from the Go original)
//! and asserts every tick matches within `TOLERANCE`.

use acacia_physics::test_world::{TestBlock, TestWorld};
use acacia_physics::{Input, Outcome, PlayerState, tick};
use serde_json::Value;

const TOLERANCE: f32 = 1e-5;

fn f(v: &Value) -> f32 {
    v.as_f64().expect("number") as f32
}

fn vec3(v: &Value) -> [f32; 3] {
    [f(&v[0]), f(&v[1]), f(&v[2])]
}

fn flag(v: &Value, key: &str) -> bool {
    v.get(key).and_then(Value::as_bool).unwrap_or(false)
}

fn int(v: &Value) -> i32 {
    v.as_i64().expect("int") as i32
}

fn build_world(fills: &Value) -> TestWorld {
    let mut w = TestWorld::new();
    for fill in fills.as_array().unwrap() {
        let kind = fill["kind"].as_str().unwrap();
        let block = if kind == "air" { None } else { Some(TestBlock::from_kind(kind).expect(kind)) };
        let p = |k: &str| [int(&fill[k][0]), int(&fill[k][1]), int(&fill[k][2])];
        w.fill(block, p("min"), p("max"));
    }
    w
}

fn input(v: &Value) -> Input {
    Input {
        move_vector: [f(&v["move"][0]), f(&v["move"][1])],
        yaw: f(&v["yaw"]),
        pitch: f(&v["pitch"]),
        jump: flag(v, "jump"),
        sneak: flag(v, "sneak"),
        want_down: false,
        sprint: flag(v, "sprint"),
        swim: flag(v, "swim"),
        glide: flag(v, "glide"),
        using_item: flag(v, "using_item"),
    }
}

fn outcome_code(o: Outcome) -> u64 {
    match o {
        Outcome::Normal => 0,
        Outcome::Teleport => 1,
        Outcome::Unloaded => 3,
        Outcome::Immobile => 4,
    }
}

/// Runs one scenario; returns its maximum absolute deviation or a description of the first mismatch.
fn run(sc: &Value) -> Result<f32, String> {
    let world = build_world(&sc["world"]);
    let mut st = PlayerState::new(vec3(&sc["start"]));
    st.on_ground = flag(sc, "on_ground");
    st.equipment.elytra = flag(sc, "elytra");
    let fx = &sc["effects"];
    st.effects.jump_boost = fx.get("jump_boost").map(int);
    st.effects.levitation = fx.get("levitation").map(int);
    st.effects.slow_falling = flag(fx, "slow_falling");
    st.effects.weaving = flag(fx, "weaving");

    let expected = sc["ticks"].as_array().unwrap();
    let mut t = 0;
    let mut max_dev = 0f32;
    for step in sc["steps"].as_array().unwrap() {
        let inp = input(&step["input"]);
        for i in 0..step["repeat"].as_u64().unwrap() {
            if i == 0 {
                if let Some(p) = step.get("teleport") {
                    st.queue_teleport(vec3(p));
                }
                if let Some(k) = step.get("knockback") {
                    st.queue_knockback(vec3(k));
                }
            }
            let out = tick(&mut st, &inp, &world);
            let e = &expected[t];
            let (pos, vel) = (vec3(&e["pos"]), vec3(&e["vel"]));
            for a in 0..3 {
                max_dev = max_dev.max((pos[a] - st.pos[a]).abs()).max((vel[a] - st.vel[a]).abs());
            }
            max_dev = max_dev.max((f(&e["fall_distance"]) - st.fall_distance).abs());
            let flags_ok = e["on_ground"] == st.on_ground
                && e["collide"][0] == st.collide_x
                && e["collide"][1] == st.collide_y
                && e["collide"][2] == st.collide_z
                && e["sneaking"] == st.sneaking
                && e["sprinting"] == st.sprinting
                && e["swimming"] == st.swimming
                && e["gliding"] == st.gliding
                && e["outcome"] == outcome_code(out.outcome);
            if max_dev > TOLERANCE || !flags_ok {
                return Err(format!(
                    "tick {t}: expected {e}\n got pos={:?} vel={:?} ground={} collide=[{},{},{}] sneak={} sprint={} swim={} glide={} fall={} outcome={:?}",
                    st.pos, st.vel, st.on_ground, st.collide_x, st.collide_y, st.collide_z, st.sneaking,
                    st.sprinting, st.swimming, st.gliding, st.fall_distance, out.outcome
                ));
            }
            t += 1;
        }
    }
    assert_eq!(t, expected.len(), "tick count");
    Ok(max_dev)
}

/// Scenarios where the port deliberately leaves bedsim from the given tick on, because BDS disagrees
/// with bedsim; see README "Deliberate deviations from bedsim".
const DELIBERATE: &[(&str, usize)] = &[
    ("sneak_toggle", 15),
    ("sneak_low_ceiling", 30),
    ("water_swim", 0),
    ("slime_walk", 0),
    ("slime_bounce", 15),
    ("ladder_climb", 15),
    ("honey_walk", 2),
    ("powder_snow", 7),
    ("elytra_glide", 106),
    ("levitation", 0),
];

#[test]
fn matches_bedsim_fixtures() {
    let data = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/bedsim.json")).unwrap();
    let scenarios: Value = serde_json::from_str(&data).unwrap();
    let mut failures = Vec::new();
    let mut overall = 0f32;
    for sc in scenarios.as_array().unwrap() {
        let name = sc["name"].as_str().unwrap();
        let deliberate = DELIBERATE.iter().find(|(n, _)| *n == name).map(|&(_, tick)| tick);
        match (run(sc), deliberate) {
            (Ok(dev), None) => {
                overall = overall.max(dev);
                println!("{name:<26} ok  max deviation {dev:e}");
            }
            (Err(msg), Some(tick)) if msg.starts_with(&format!("tick {tick}:")) => println!("{name:<26} deviates from tick {tick} as intended"),
            (Ok(_), Some(tick)) => failures.push(format!("{name}: no longer deviates at tick {tick}; drop it from DELIBERATE")),
            (Err(msg), _) => failures.push(format!("{name}: {msg}")),
        }
    }
    println!("overall max deviation {overall:e}");
    assert!(failures.is_empty(), "{} scenario(s) diverged:\n{}", failures.len(), failures.join("\n\n"));
}
