//! Groups emitted items into files and writes the `generated/` tree.

use std::fs;
use std::path::Path;
use std::process::Command;

use crate::emit_read::Ctx;
use crate::ir::*;

/// Unformatted bytes per part file; keeps each formatted file in the low thousands of lines.
const PART_BUDGET: usize = 60_000;

const HEADER: &str = "// @generated by acacia-codegen from tools/codegen/data/protocol.json. Do not edit; see docs/proto.md.\n";

pub struct Version {
    pub protocol: i64,
    pub game: String,
}

pub fn write_all(out: &Path, items: &[Item], version: &Version) -> Vec<std::path::PathBuf> {
    if out.exists() {
        fs::remove_dir_all(out).expect("clear generated dir");
    }
    let mut files = Vec::new();
    for (module, dir, prelude) in [
        (Module::Types, "types", "use super::*;\n"),
        (
            Module::Packets,
            "packets",
            "use super::*;\nuse crate::types;\n",
        ),
    ] {
        let ctx = Ctx { items, module };
        let parts = split_parts(&ctx, module);
        let dir_path = out.join(dir);
        fs::create_dir_all(&dir_path).expect("create generated dir");
        let mut mod_rs = String::from(HEADER);
        for (i, body) in parts.iter().enumerate() {
            let file = format!("part_{i:02}");
            mod_rs += &format!("mod {file};\npub use {file}::*;\n");
            let src = format!(
                "{HEADER}{prelude}use crate::codec::*;\nuse crate::DecodeError;\nuse bytes::{{Bytes, BytesMut}};\n\n{body}"
            );
            files.push(write(&dir_path.join(format!("{file}.rs")), &src));
        }
        files.push(write(&dir_path.join("mod.rs"), &mod_rs));
    }
    let mut packets: Vec<(u32, &str)> = items
        .iter()
        .filter_map(|i| i.packet.as_ref().map(|(id, _)| (*id, i.name.as_str())))
        .collect();
    packets.sort();
    let list: Vec<&str> = packets.iter().map(|(_, n)| *n).collect();
    let root = format!(
        "{HEADER}#![allow(unused_parens, unused_imports, unused_variables, clippy::all)]\n\n\
         pub const PROTOCOL_VERSION: i32 = {};\npub const GAME_VERSION: &str = {:?};\n\npub mod packets;\npub mod types;\n\n\
         /// Invokes `$m!(Login, PlayStatus, ...)` with every packet type in id order (for dispatch tables and tests).\n\
         #[macro_export]\nmacro_rules! for_each_packet {{\n($m:ident) => {{\n$m!({});\n}};\n}}\n",
        version.protocol,
        version.game,
        list.join(", ")
    );
    files.push(write(&out.join("mod.rs"), &root));
    files
}

/// Concatenates each root's items (a top-level type/packet plus everything hoisted from it), chunked by size.
fn split_parts(ctx: &Ctx, module: Module) -> Vec<String> {
    let mut ids: Vec<ItemId> = (0..ctx.items.len())
        .filter(|&i| ctx.items[i].module == module)
        .collect();
    ids.sort_by_key(|&i| (ctx.items[i].root, i));
    let mut parts = vec![String::new()];
    let mut prev_root = None;
    for id in ids {
        let root = ctx.items[id].root;
        if prev_root != Some(root) && parts.last().unwrap().len() > PART_BUDGET {
            parts.push(String::new());
        }
        prev_root = Some(root);
        let part = parts.last_mut().unwrap();
        part.push_str(&ctx.item(id));
        part.push('\n');
    }
    parts
}

fn write(path: &Path, src: &str) -> std::path::PathBuf {
    fs::write(path, src).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
    path.to_owned()
}

pub fn rustfmt(files: &[std::path::PathBuf]) {
    let status = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .args(files)
        .status();
    match status {
        Ok(s) if s.success() => {}
        Ok(s) => panic!("rustfmt failed ({s}); generated code is probably malformed"),
        Err(e) => eprintln!("warning: rustfmt not run ({e}); output is unformatted"),
    }
}
